### PR TITLE
Link nested swift files

### PR DESCRIPTION
**Pull request by uen**
Removes single-level limitation of swift files, creates groups based on directory structure 

https://github.com/EvanBacon/expo-apple-targets/issues/46

### CODE REVIEW

**Comment by uen** [comment]
@EvanBacon Could you please take a look at this 🙏

**Comment by wodin** [comment]
> @EvanBacon Could you please take a look at this 🙏

image

**Comment by uen** [comment]
thanks @wodin 
Screenshot 2024-10-25 at 16 09 56

**Review by EvanBacon — APPROVED** [review]
probably need to start adding tests

**Pull request merged**
