### PR TITLE
add AppIntent ExtensionType

### PR DESCRIPTION
**Pull request by lukesthl**
This extension adds support for [iOS AppIntents](https://developer.apple.com/documentation/appintents). This is a new way for creating Shortcuts via the App Intent Framework introduced in iOS 16. It kind of replaces the older siri app intent target: https://developer.apple.com/documentation/widgetkit/migrating-from-sirikit-intents-to-app-intents

Also added an example app intent folder.

### CODE REVIEW

**Comment by lukesthl** [comment]
@buraks i used it as a custom package in this repo: [https://github.com/lukesthl/digital-break-app/tree/main/packages/target-plugin](https://github.com/lukesthl/digital-break-app/tree/main/packages/target-plugin) 
It should work properly. I only made minor adjustments to ensure compatibility with this monorepo, but I haven't used it since the last commit.

**Comment by k2on** [comment]
This would be really nice

**Comment by k2on** [comment]
+1

**Comment by wodin** [comment]
@k2on you will probably have more luck sending [`@Baconbrix`](https://x.com/Baconbrix/status/1763772946517049590) a meme on Twitter asking him to take a look
skeleton waiting meme

**Comment by k2on** [comment]
@wodin 💀 I made this in the meantime [https://www.npmjs.com/package/bacons-apple-targets-intents](https://www.npmjs.com/package/bacons-apple-targets-intents)

**Comment by buraks** [comment]
@EvanBacon  any chance that you can merge this in? 🙃

**Comment by wodin** [comment]
@buraks unless something has changed in the last few months:
image

**Comment by EvanBacon** [comment]
Closing in favor of https://github.com/EvanBacon/expo-apple-targets/pull/58. Mirrored due to the rewrite and because a number of these changes belonged in the upstream bacons/xcode package. Thanks for the contribution.

**Pull request closed without merging**
